# test this file with
#   GITHUB_USER=jpillora goreleaser --skip-publish --rm-dist --config .github/goreleaser.yml
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    goarm:
      - '6'
      - '7'
nfpms:
  - maintainer: "https://github.com/{{ .Env.GITHUB_USER }}"
    formats:
      - deb
      - rpm
      - apk
archives:
  - format: gz
    files:
      - none*
    rlcp: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
