name: Auto-approve and merge Dependabot updates

on:
  pull_request:
    branches: [master]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Approve Dependabot PR
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump minor tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Get the latest tag
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")

          # Parse the tag into major, minor, patch
          if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            
            # Increment the minor version
            new_minor=$((minor + 1))
            new_tag="v${major}.${new_minor}.0"
            
            # Create and push the new tag
            echo "Bumping $latest_tag to $new_tag"
            git tag -a "$new_tag" -m "Bump minor version for dependency update"
            git push origin "$new_tag"
          else
            echo "No valid semver tag found, creating v0.1.0"
            git tag -a "v0.1.0" -m "Initial tag for dependency update"
            git push origin "v0.1.0"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
